# Generated by Django 5.1.3 on 2024-11-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_created_models_for_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
    ]
