# Generated by Django 5.1.3 on 2024-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_delete_status_from_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
